import { combineReducers } from 'redux'
import { AptitudeBarReducer, AptitudeCcpReducer, AptitudeEsqReducer, AptitudeInitReducer, AptitudeMcritReducer, AptitudeMdistReducer, AptitudeMdosReducer, AptitudeMelemReducer, AptitudeMmeleeReducer, AptitudeMmonoReducer, AptitudeMsoinReducer, AptitudeMzerkReducer, AptitudeMzoneReducer, AptitudeParadeReducer, AptitudePvarReducer, AptitudePvReducer, AptitudeRcritReducer, AptitudeRdosReducer, AptitudeResReducer, AptitudeSoinrReducer, AptitudeTacesqReducer, AptitudeTacReducer, AptitudeVolReducer,AptitudePAReducer, AptitudePMReducer, AptitudePOReducer, AptitudePWReducer, AptitudeCtrlReducer, AptitudeRelemReducer, AptitudeDIReducer, AptitudePdvReducer } from './aptitudeReducer'
import { amuReducer, anneau1Reducer, anneau2Reducer, bottesReducer, BuildlevelReducer, capeReducer, casqueReducer, ceintureReducer, chosenTypeReducer, classeReducer, emblemeReducer, epauReducer, familierReducer, mainReducer, montureReducer, plastronReducer, secondemainReducer } from './buildReducers'
import { itemReducer, loadReducer } from './resultReducer'
import {levelReducer,typeReducer,rarityReducer} from './SearchReducer'

const allReducers = combineReducers({
    level : levelReducer,
    type : typeReducer,
    rarity : rarityReducer,
    classe: classeReducer,
    casque:casqueReducer,
    cape: capeReducer,
    amu: amuReducer,
    epau: epauReducer,
    plastron:plastronReducer,
    ceinture:ceintureReducer,
    anneau1: anneau1Reducer,
    anneau2: anneau2Reducer,
    bottes:bottesReducer,
    familier:familierReducer,
    secondemain:secondemainReducer,
    main:mainReducer,
    embleme:emblemeReducer,
    monture:montureReducer,
    Buildlevel:BuildlevelReducer,
    item:itemReducer,
    load:loadReducer,
    chosen:chosenTypeReducer,
    Apv:AptitudePvReducer,
    Ares:AptitudeResReducer,
    Abar:AptitudeBarReducer,
    Asoinr:AptitudeSoinrReducer,
    Apvar:AptitudePvarReducer,
    Amelem:AptitudeMelemReducer,
    Ammono:AptitudeMmonoReducer,
    Amzone:AptitudeMzoneReducer,
    Ammelee:AptitudeMmeleeReducer,
    Amdist:AptitudeMdistReducer,
    Apdv:AptitudePdvReducer,
    Atac:AptitudeTacReducer,
    Aesq:AptitudeEsqReducer,
    Aini:AptitudeInitReducer,
    Atacesq:AptitudeTacesqReducer,
    Avol:AptitudeVolReducer,
    Accp:AptitudeCcpReducer,
    Aparade:AptitudeParadeReducer,
    Amcrit:AptitudeMcritReducer,
    Amdos:AptitudeMdosReducer,
    Amzerk:AptitudeMzerkReducer,
    Amsoin:AptitudeMsoinReducer,
    Ardos:AptitudeRdosReducer,
    Arcrit:AptitudeRcritReducer,
    Apa:AptitudePAReducer,
    Apm:AptitudePMReducer,
    Apo:AptitudePOReducer,
    Apw:AptitudePWReducer,
    Actrl:AptitudeCtrlReducer,
    Adi:AptitudeDIReducer,
    Arelem:AptitudeRelemReducer
})
export default allReducers